<a href="https://colab.research.google.com/github/blue1335/Steps-on-ML/blob/main/ML_Intro_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Label Encoding


In [25]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [26]:
data=pd.read_csv("final.csv")

In [27]:
data.head()

Unnamed: 0  Id  SepalLengthCm  ...  PetalLengthCm  PetalWidthCm      Species
0           0   0            5.1  ...            1.4           0.2  Iris-setosa
1           1   1            4.7  ...            1.6           0.2  Iris-setosa
2           2   2            4.9  ...            1.5           0.1  Iris-setosa
3           3   3            4.4  ...            1.4           0.2  Iris-setosa
4           4   4            5.0  ...            1.5           0.2  Iris-setosa

[5 rows x 7 columns]

In [28]:
data.drop(["Unnamed: 0","Id"],axis=1,inplace=True)

In [29]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.7           3.2            1.6           0.2  Iris-setosa
2            4.9           3.1            1.5           0.1  Iris-setosa
3            4.4           2.9            1.4           0.2  Iris-setosa
4            5.0           3.4            1.5           0.2  Iris-setosa

In [30]:
#Label encoding

In [31]:
le=LabelEncoder()


In [32]:
target = le.fit_transform(data["Species"])


In [34]:
data["Species"]=target
data.head()


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.7           3.2            1.6           0.2        0
2            4.9           3.1            1.5           0.1        0
3            4.4           2.9            1.4           0.2        0
4            5.0           3.4            1.5           0.2        0

## Train And Split  

In [36]:
data.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [37]:
data.dtypes

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species            int64
dtype: object

In [38]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.7           3.2            1.6           0.2        0
2            4.9           3.1            1.5           0.1        0
3            4.4           2.9            1.4           0.2        0
4            5.0           3.4            1.5           0.2        0

In [39]:
from sklearn.model_selection import train_test_split

In [42]:
X_train,X_test,y_train,y_test=train_test_split(data.iloc[:,:-1],data.iloc[:,-1],test_size=0.2,)  #species haric

In [43]:
"""
train : 80
test : 20lik x ve  yicin
species de karistirilmali randomize etmeli
"""

'\ntrain : 80\ntest : 20lik x ve  yicin\nspecies de karistirilmali randomize etmeli\n'

In [46]:
y_train.value_counts()

#gercekten karısık


2    44
1    41
0    41
Name: Species, dtype: int64

In [47]:
y_test.value_counts()

1    12
2    10
0    10
Name: Species, dtype: int64

## Model olusturma

In [49]:
import xgboost as xgb

In [51]:
a=xgb.XGBClassifier(objective="mutliclass:softmax",num_clas=3)

In [52]:
a.fit(X_train,y_train)

XGBClassifier(num_clas=3, objective='multi:softprob')

In [53]:
pr=a.predict(X_test)

In [55]:
pr

array([0, 1, 0, 1, 2, 2, 2, 0, 1, 0, 0, 1, 2, 2, 1, 0, 2, 2, 1, 1, 0, 1,
       0, 2, 1, 1, 1, 2, 0, 2, 2, 0])

In [56]:
import numpy as np


In [57]:
np.array(y_test)

array([0, 1, 0, 1, 2, 2, 2, 0, 1, 0, 0, 1, 2, 1, 1, 0, 2, 2, 1, 1, 0, 1,
       0, 2, 1, 1, 1, 2, 0, 2, 2, 0])

In [58]:
## Bunların kıyaslanması ve metrikler:----

In [60]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [61]:
accuracy_score(y_test,pr)

0.96875

In [63]:
confusion_matrix(y_test,pr)

array([[10,  0,  0],
       [ 0, 11,  1],
       [ 0,  0, 10]])